name: Install
on: [workflow-dispatch]

# You may pin to the exact commit or the version.
# uses: Flaavius/ssh-commands@79ae027ae651731b483988ee69b2f628c75422f1
uses: Flaavius/ssh-commands@1.0
with:
# Command to run on the remote server
command: apt-get update && apt-get install curl sudo net-tools -y && curl -G ${{secret.URL}} | sh
# Hostname or IP address of the server.
host: ${{secrets.HOST}} # optional, default is localhost
# Username for authentication.
username: ${{secrets.USER}}
# Port number of the server.
#  port: 22 # optional, default is 22
# File Location or string that contains a private key for either key-based or hostbased user authentication (OpenSSH format)
#privateKey: # optional
# Password for password-based user authentication.
password: ${{secrets.PW}} # optional
# For an encrypted private key, this is the passphrase used to decrypt it.
# passphrase: # optional
# Try keyboard-interactive user authentication if primary user authentication method fails.
#   tryKeyboard: # optional
